-- Run as ACCOUNTADMIN. Caps total compute at 5 credits/month across all warehouses.
CREATE RESOURCE MONITOR transit_monthly
  WITH CREDIT_QUOTA = 5
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE COMPUTE_WH SET RESOURCE_MONITOR = transit_monthly, AUTO_SUSPEND = 60;
ALTER WAREHOUSE SNOWFLAKE_LEARNING_WH SET RESOURCE_MONITOR = transit_monthly, AUTO_SUSPEND = 60;
ALTER WAREHOUSE SYSTEM$STREAMLIT_NOTEBOOK_WH SET RESOURCE_MONITOR = transit_monthly;

-- Verify
SHOW RESOURCE MONITORS;
SHOW WAREHOUSES;
